---
title: "LA_Data_Cleaning"
author: "Nam Tran"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(tidyverse); library(dplyr); library(psych); library(PerformanceAnalytics); library(skimr); library(lessR); library(ggplot2); library(gridExtra); library(fastDummies); library(forecast); library(BMA); library(stats); library(olsrr); library(MASS); library(kableExtra); library(car); library(broom); library(glmulti); library(ggmap); library(rstudioapi); library(revgeo); library(RCurl)
```

```{r}
LA_raw <- read.csv("LA_listings.csv")
dim(LA_raw)
```

The dataset includes all LA listings that are scraped from Airbnb website on December 2021. There are 33329 observations and 74 variables.

```{r}
# Remove some unnecessary variables.
drop <- c("listing_url","scrape_id","last_scraped","picture_url","host_url","host_thumbnail_url","host_picture_url","host_listings_count","host_verifications","host_neighbourhood","bathrooms","minimum_nights","maximum_nights","minimum_minimum_nights","maximum_minimum_nights","maximum_minimum_nights","maximum_maximum_nights","minimum_nights_avg_ntm","maximum_nights_avg_ntm","calendar_updated","has_availability","availability_30","availability_60","availability_90","availability_365","calendar_last_scraped","license","host_name","host_location","host_about","minimum_maximum_nights")

LA_Clean1_Dec <- LA_raw[,!(names(LA_raw) %in% drop)]
```

```{r}
dim(LA_Clean1_Dec)

```

```{r}
str(LA_Clean1_Dec)
```


```{r}
count(unique(LA_Clean1_Dec["id"]))
count(unique(LA_Clean1_Dec["host_id"]))
# All listings are unique
```

## Checking missing values

```{r}
as.data.frame(colSums(is.na(LA_Clean1_Dec)))
as.data.frame(colMeans(is.na(LA_Clean1_Dec))*100)
```

## Checking Wrong data type

```{r}
# Changing the datatype of Price variable into numeric
LA_Clean1_Dec$price = gsub("\\$","",LA_Clean1_Dec$price)
LA_Clean1_Dec$price = gsub(",","",LA_Clean1_Dec$price)
LA_Clean1_Dec$price <- as.numeric(LA_Clean1_Dec$price)

```

### Price
```{r}
# How many listings have $ 0.0 of price
count(LA_Clean1_Dec[LA_Clean1_Dec$price == 0,])
# There are 16 listings that have $ 0.0 of price.
```

### host_response_rate
```{r}
# Changing the datatype of host_response_rate variable into numeric
LA_Clean1_Dec$host_response_rate = as.numeric(sub("%","",LA_Clean1_Dec$host_response_rate))/100
LA_Clean1_Dec["host_response_rate"]
```

### host_acceptance_rate
```{r}
# Changing the datatype of host_acceptance_rate variable into numeric
LA_Clean1_Dec$host_acceptance_rate = as.numeric(sub("%","",LA_Clean1_Dec$host_acceptance_rate))/100
LA_Clean1_Dec["host_acceptance_rate"]
```


```{r}
#Save the cleaned data to another file for using later.
write.csv(LA_Clean1_Dec,"LA_Clean1_Dec.csv", row.names = F)
```

```{r}
Address_df <- read.csv("Address_Dec.csv")
```

```{r}
Listing_Clean1_Dec <- cbind(LA_Clean1_Dec, Address_df[,c(4,5,6)])
Listing_Clean1_Dec
```

```{r}
write.csv(Listing_Clean1_Dec,"Airbnb_DataCleaning1.csv", row.names = F)
```


