---
title: "HostAnalysisOverTime"
author: "Nhat My Thien Nguyen"
date: "4/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(tidyverse); library(dplyr); library(psych); library(PerformanceAnalytics); library(skimr); library(lessR); library(ggplot2); library(gridExtra); library(fastDummies); library(forecast); library(BMA); library(stats); library(olsrr); library(MASS); library(kableExtra); library(car); library(broom); library(glmulti); library(ggmap); library(rstudioapi); library(revgeo); library(RCurl);library(stringr); library(gsubfn);library(ngram);library(stringr); library(tm); library(caret); library(ROCR); library(ROSE)
```

```{r}
Listing_6_9_12 <- read.csv("Listing_6_9_12.csv")
head(Listing_6_9_12)
```

```{r}
dim(Listing_6_9_12)
as.data.frame(colSums(is.na(Listing_6_9_12)))
```

```{r}
Listing_6_9_12 <- Listing_6_9_12[!is.na(Listing_6_9_12$June),]
Listing_6_9_12 <- Listing_6_9_12[!is.na(Listing_6_9_12$September),]
Listing_6_9_12 <- Listing_6_9_12[!is.na(Listing_6_9_12$December),]
as.data.frame(colSums(is.na(Listing_6_9_12)))
```

# Probability of Super Host return back to Normal Host
```{r}
model1_df <- Listing_6_9_12
```
```{r}
model1_df$Y <- ifelse(model1_df$Status =="SH-SH-H" |model1_df$Status == "SH-H-H", 1,0 )
colnames(model1_df)
```
```{r}
set.seed(123)

## partitioning into training (70%), validation (30%)
train1.index <- sample(rownames(model1_df), dim(model1_df)[1]*0.7)  # randomly sample 70% of the row IDs for training
valid1.index <- setdiff(rownames(model1_df), train1.index)           # use setdiff() to find records not already in the training set

# create the 2 data frames by collecting all columns from the appropriate rows
train1.df <- model1_df[train1.index,6:26]
valid1.df <- model1_df[valid1.index,6:26 ]

```

## Oversampling
```{r}
table(train1.df$Y)            
prop.table(table(train1.df$Y)) 
```
```{r}
train.df.over<-ovun.sample(Y~.,data=train1.df,method="over",N=18000)$data
table(train.df.over$Y)
```

```{r}
logit1_os_model <- glm(Y ~ ., data = train.df.over, family = "binomial")
summary(logit1_os_model)
```
```{r}
logit1.pred.os<- predict(logit1_os_model, valid1.df,type="response")
confusionMatrix(as.factor(ifelse(logit1.pred.os>0.5, 1 ,0)),as.factor(valid1.df$Y),positive = "1")
```

```{r}
coeff_over_df <- as.data.frame(summary(logit1_os_model)$coefficient)
coeff_over_df$Indicators <- rownames(coeff_over_df)
sig_coef_over_df <- coeff_over_df[coeff_over_df[,4]<= 0.05, c(5,1,2,3,4)]
sig_coef_over_df
```

```{r}
write.csv(sig_coef_over_df[-1,], "sig_coef_over_df.csv", row.names = F, )
```


# Probability of SuperHosts remains their status overtime
```{r}
model2_df <- Listing_6_9_12
```
```{r}
model2_df$Y <- ifelse(model2_df$Status =="SH-SH-SH" |model2_df$Status == "SH-H-SH", 1,0 )
```

```{r}
set.seed(123)
## partitioning into training (70%), validation (30%)
train2.index <- sample(rownames(model2_df), dim(model2_df)[1]*0.7)  # randomly sample 70% of the row IDs for training
valid2.index <- setdiff(rownames(model2_df), train2.index)           # use setdiff() to find records not already in the training set
```

```{r}
# create the 2 data frames by collecting all columns from the appropriate rows
train2.df <- model2_df[train2.index,6:26]
valid2.df <- model2_df[valid2.index,6:26 ]
```

```{r}
table(train2.df$Y)            
prop.table(table(train2.df$Y))
```

```{r}
logit2_model <- glm(Y ~ ., data = train2.df, family = "binomial")
summary(logit2_model)
```
```{r}
logit.pred2<- predict(logit2_model, valid2.df,type="response")
confusionMatrix(as.factor(ifelse(logit.pred2>0.5, 1 ,0)),as.factor(valid2.df$Y),positive = "1")
```

# Probability of Hosts remain their status overtime

```{r}
model3_df <- Listing_6_9_12
```
```{r}
model3_df$Y <- ifelse(model3_df$Status =="H-H-H" |model3_df$Status == "H-SH-H", 1,0 )
```
```{r}
set.seed(123)

## partitioning into training (70%), validation (30%)
train3.index <- sample(rownames(model3_df), dim(model3_df)[1]*0.7)  # randomly sample 70% of the row IDs for training
valid3.index <- setdiff(rownames(model3_df), train3.index)           # use setdiff() to find records not already in the training set
```
```{r}
# create the 2 data frames by collecting all columns from the appropriate rows
train3.df <- model3_df[train3.index,6:26]
valid3.df <- model3_df[valid3.index,6:26 ]
```

```{r}
table(train3.df$Y)            
prop.table(table(train3.df$Y))
```
```{r}
logit3_model <- glm(Y ~ ., data = train3.df, family = "binomial")
summary(logit3_model)
```
```{r}
logit.pred3<- predict(logit3_model, valid3.df,type="response")
confusionMatrix(as.factor(ifelse(logit.pred3>0.5, 1 ,0)),as.factor(valid3.df$Y),positive = "1")
```






















