---
title: "Model1_city"
author: "Nam Tran"
date: "4/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr); library(tidyverse); library(dplyr); library(psych); library(PerformanceAnalytics); library(skimr); library(lessR); library(ggplot2); library(gridExtra); library(fastDummies); library(forecast); library(BMA); library(stats); library(olsrr); library(MASS); library(kableExtra); library(car); library(broom); library(glmulti); library(ggmap); library(rstudioapi); library(revgeo); library(RCurl);library(stringr); library(gsubfn);library(ngram);library(stringr); library(tm); library(caret); library(ROCR); library(ROSE)
```

```{r}
df <- read.csv("Airbnb_DataCleaning3.csv")
# str(df)
```

```{r}
colnames(df)
```

```{r}
model_city <- df[,c("host.is.superhost", "City")]
model_city$City <- sub(" ","_",model_city$City )
model_city$City <- sub("-","_",model_city$City )
model_city$City <- sub(" ","_",model_city$City )
model_city$City <- as.factor(model_city$City)
```


```{r}
model_city <- fastDummies::dummy_cols(model_city, select_columns = c("host.is.superhost") , remove_first_dummy = TRUE)
head(model_city)
```

```{r}
model_city1 <- model_city[,2:3]
model_city1 <- within(model_city1, City <- relevel(City, ref = "Los_Angeles"))
```

```{r}
set.seed(123)

## partitioning into training (70%), validation (30%)
train_city.index <- sample(rownames(model_city1), dim(model_city1)[1]*0.7)  # randomly sample 70% of the row IDs for training
valid_city.index <- setdiff(rownames(model_city1), train_city.index)           # use setdiff() to find records not already in the training set

# create the 2 data frames by collecting all columns from the appropriate rows
train_city.df <- model_city1[train_city.index, ]
valid_city.df <- model_city1[valid_city.index, ]

dim(train_city.df)
```

```{r}
table(train_city.df$host.is.superhost_t)
train_city.df.over<-ovun.sample(host.is.superhost_t~.,data=train_city.df,method="over",N=32478)$data
table(train_city.df.over$host.is.superhost_t)
```
```{r}
unique(model_city1$City)
```


```{r}
logit_city_model <- glm(host.is.superhost_t ~ ., data = train_city.df.over, family = "binomial", )
summary(logit_city_model)
```

```{r}

```

```{r}
logit.pred.city <- predict(logit_city_model, valid_city.df,type="response")
confusionMatrix(as.factor(ifelse(logit.pred.city>0.5, 1 ,0)),as.factor(valid_city.df$host.is.superhost_t),positive = "1")
```

